- greeting:
    text_size: xl
    text: "{{HOMEPAGE_VAR_GREETING}}"

- datetime:
    text_size: xl
    format:
      timeStyle: short

- resources:
    cpu: true
    memory: true
    expanded: true
    disk: /
    cputemp: true
    tempmin: 20
    tempmax: 80
    uptime: true
    units: metric # only used by cpu temp
    refresh: 3000 # optional, in ms
    diskUnits: bytes # optional, bytes (default) or bbytes. Only applies to disk
